# Generated by Django 6.0.4 on 2026-07-17 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='run_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
